executable = /home/julisuvk/recourse/_venv/bin/python
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 65536
request_cpus = 4



arguments = main.py --scm_class fair-IMF-LIN --classifier_class cw_fair_svm --lambda_lcb 1 --optimization_approach brute_force --grid_search_bins 15 -e 9 --sensitive_attribute_nodes x1 --num_train_samples 500 --num_fair_samples 50 --fair_kernel_type all --batch_number 0 --sample_count 200